---
kind: pipeline
type: docker
name: wirez-ci

trigger:
  ref:
    - refs/heads/main
    - refs/pull/*/head
    - refs/tags/*
  event:
    - push
    - tag
    - pull_request

clone:
  depth: 1

steps:
  - name: lint
    image: golangci/golangci-lint:v1.49-alpine
    volumes:
      - name: deps
        path: /go
    commands:
      - golangci-lint run -v
      - go install github.com/mgechev/revive@v1.2.3
      - revive -config .revive.toml -formatter friendly ./...

  - name: test & build
    image: golang:1.19-alpine
    environment:
      CGO_ENABLED: "0"
    volumes:
      - name: deps
        path: /go
    commands:
      - go test ./... -v -cover
      - go build -ldflags "-w -s"

volumes:
  - name: deps
    temp: {}
