linters:
  enable:
    - dogsled
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - staticcheck
    - govet
    - misspell
    - nestif
    - prealloc
    - revive
    - unconvert
    - unparam

linters-settings:
  revive:
    max-open-files: 2048
    ignore-generated-header: true
    severity: warning
    confidence: 0.8

run:
  timeout: 5m