project_name: wirez
gomod:
  proxy: true
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - files:
      - none*
checksum:
  algorithm: sha256
changelog:
  sort: asc
  filters:
    exclude:
      - '^(\s)*docs:'
      - '^(\s)*test:'
      - Merge pull request
      - update README
